name: qotdpy Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push latest
      if: contains(github.ref_name, 'main')
      id: docker_build_main
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:buildcache,mode=max
    - name: Build and push latest
      if: false == contains(github.ref_name, 'main')
      id: docker_build_tag
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:${{github.ref_name}}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qotdpy:buildcache,mode=max
    - name: Image digest
      if: contains(github.ref_name, 'main')
      run: echo ${{ steps.docker_build_main.outputs.digest }}
    - name: Image digest
      if: false == contains(github.ref_name, 'main')
      run: echo ${{ steps.docker_build_tag.outputs.digest }}
